FROM ubuntu

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install -y mosquitto-clients
RUN apt-get install -y python3-pip
RUN pip3 install paho-mqtt

RUN mkdir im_proc
COPY . /im_proc
WORKDIR /im_proc

ENTRYPOINT ["python3"]
CMD ["im_proc.py"]
